### PR TITLE
Casting resultset to native PHP types

### PR DESCRIPTION
**Pull request by codercms**
According to this PR - https://github.com/php/php-src/pull/4939

### CODE REVIEW

**Comment by codercms** [comment]
@twose could you review this PR?
This PR makes Postgres Client to return values in native PHP types instead of only strings.

**Comment by twose** [comment]
@yunnian is the author of ext-PostgreSQL

and call @matyhtf and @huanghantao too

anyway, it looks good to me, thank you for your contribution

**Comment by yunnian** [comment]
Let's discuss whether it's better to add an option, such as：

>  $mysqli->options(MYSQLI_OPT_INT_AND_FLOAT_NATIVE, 1);

**Comment by codercms** [comment]
@yunnian do we have any reasons to add custom parameter that toggles float/int conversion?

**Pull request merged**
